---
# Per environment values which override defaults in hmpps-document-generation-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: document-generation-api-dev.hmpps.service.justice.gov.uk

  env:
    SPRING_PROFILES_ACTIVE: dev
    SENTRY_ENVIRONMENT: dev

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: move-and-improve-alerts-non-prod
  rdsAlertsDatabases:
    cloud-platform-348213e2359f7b4e: "Document Generation API"
  rdsAlertsConnectionThreshold: 40
