---
# Per environment values which override defaults in hmpps-document-generation-api/values.yaml

generic-service:
  ingress:
    host: document-generation-api.hmpps.service.justice.gov.uk

  env:
    SPRING_PROFILES_ACTIVE: prod
    SENTRY_ENVIRONMENT: prod

  scheduledDowntime:
    enabled: false

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: move-and-improve-alerts
