generic-service:
  nameOverride: hmpps-document-generation-api
  productId: "DPS125" # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  replicaCount: 2
  resources:
    requests:
      cpu: 128m
      memory: 1024Mi
    limits:
      cpu: 2048m
      memory: 1280Mi

  image:
    repository: ghcr.io/ministryofjustice/hmpps-document-generation-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-document-generation-api-cert

  # Used to access resources like S3 buckets, SQS queues and SNS topics
  serviceAccountName: hmpps-document-generation-api

  # Environment variables to load into the deployment
  env:
    JDK_JAVA_OPTIONS: "-javaagent:/agent/agent.jar -Xmx512m -XX:+UseG1GC"
    SERVER_PORT: "8080"
    DB_SSL_MODE: "verify-full"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    SENTRY_TRACES_SAMPLE_RATE: '0.05'
    SENTRY_IGNORED_EXCEPTIONS_FOR_TYPE: "org.apache.catalina.connector.ClientAbortException,org.springframework.web.servlet.resource.NoResourceFoundException,org.springframework.web.context.request.async.AsyncRequestNotUsableException"

  namespace_secrets:
    hmpps-document-generation-api-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    hmpps-document-generation-api-sentry:
      SENTRY_DSN: SENTRY_DSN
      SENTRY_AUTH_TOKEN: SENTRY_AUTH_TOKEN
    hmpps-document-generation-api:
      CLIENT_ID: "SYSTEM_CLIENT_ID"
      CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
    hmpps-document-generation-api-postgres:
      DB_SERVER: "database_server"
      DB_NAME: "database_name"
      DB_USER: "database_username"
      DB_PASS: "database_password"

  allowlist:
    groups:
      - digital_staff_and_mojo
      - moj_cloud_platform

  scheduledDowntime:
    enabled: true
    startup: '30 6 * * 1-5'
    shutdown: '30 21 * * 1-5'

generic-prometheus-alerts:
  targetApplication: hmpps-document-generation-api
